### ISSUE TITLE
[1.10] Recipe problem.

### ISSUE THREAD

**Issue by phrostt** [TechReborn/TechReborn#1078]
This may or may not be a bug, but I cant seem to find a solution. According to JEI a compressed air cell from techreborn can be turned back into an empty cell in an extractor. Industrial craft extractor does not accept the cell and techreborn extractor doesnt seem to exist, despite JEI claiming it does.

**Comment by phrostt** [comment]
After further inspection it seems that this issue is true for many other cells, there is no extractor and the IC2 extractor does not take any of them.

**Comment by Skillotic0703** [comment]
What version are you using? I'm using the latest version for 1.10.2 and the extractor from techreborn seems to exist. Also check your config files because there is an option in techreborn that allows you to not load the duplicate content when IC2 is loaded. This option is still WIP so it may be the reason why it's not working.
