### ISSUE TITLE
1 EU == 4 FE == ... 1RF...? (and other cable weirdness)

### ISSUE THREAD

**Issue by Vectrobe** [TechReborn/TechReborn#1230]
1 RF appears to be taken in as 4 FE, instead of just 1...
While the other way round, FE to RF, has varying factors between devices (tiers?), and will output at a rounding loss, some examples;
- MFSU with 4200FE will output 512RF, 8x decrease
- MFE with 4300FE will output 318RF, 13.5x decrease
- battbox has the same ratio as MFE
these devices also exhibit similar behaviour with low tiers of TR cables, suggesting a stacking effect.

**Comment by Skillotic0703** [comment]
I think that there are general energy problems in TechReborn atm. So it would be cool to find a solution for that!

**Comment by drcrazy** [comment]
@Paul17041993  can you recheck plz? And if it is possible can you describe how you checking this, please?

**Comment by Vectrobe** [comment]
- connecting an RF source, such as an energy cell or fluxduct, to a TR machine would result in 4FE per 1 RF, but when  the flow is reversed the conversion is extremely lossy...
- TR cables would transport FE in weird ways...

haven't tested the latest builds as of yet...

**Comment by drcrazy** [comment]
I've set energy cell. Filled it in and connected electrolyzer via fluxducts. Upon connection it drained more than expected but i'm not sure about reason for that because fluxducts energy jumped from 5k RF to 10k RF. Then I replenished cell to 2M RF once again. And used electrolyzer once to produce electrolyzed water cell. According to recipe it should take 4k RF. And it took 4k RF from cell.

![image](https://user-images.githubusercontent.com/1382352/30525954-2f696d78-9c1a-11e7-9a1b-6f8f6a799b4c.png)

If issue will persist, please, report a new one for specific machine.
