### ISSUE TITLE
TechReborn crashing with IC2

### ISSUE THREAD

**Issue by Shattered2909** [TechReborn/TechReborn#1458]
Using those versions:
TechReborn-1.12.2-12.5.501-universal
RebornCore-1.12.2-3.6.11.220-universal
industrialcraft2-2.8.66-ex112

So i was updating a few mods for the pack i am currently working on and got a crash with an ic2 recipe. Contacted their dev, they said it is caused by another mod, so i thought it's metals, but it wasn't either. Decided to create a testing instance which worked until i added Techreborn and Reborn Core (versions above). The crashlog at the bottom is what happened, something related to a recipe conflict with iridium. I should probably mention that in my pack, the ic2 integration is enabled but in the testing instance it is not. Maybe you know what is wrong here.

[crash-2018-03-18_12.50.20-client.txt](https://github.com/TechReborn/TechReborn/files/1822630/crash-2018-03-18_12.50.20-client.txt)

**Comment by modmuss50** [comment]
Humm, looks like ic2 may have updated things. I will have to do some testing.

**Comment by modmuss50** [comment]
Can you try with just IC2, RebornCore and TechReborn? As I just updated to the latest ic2 and it doesn't happen for me.

**Comment by Shattered2909** [comment]
That works, but it starts crashing once i add the metals package.

**Comment by dshadowwolf** [comment]
Issue is multi-part and odd in that it requires TR, IC2 and ModernMetals (w/ModernMetals provided Iridium active). Seems that the IC2 recipe loader for the Macerator works fine when TR or ModernMetals is not present, but when both are, it seems that the IC2 recipe code for the macerator breaks.

This is being fixed in ModernMetals as the solution is to have it such that ModernMetals does not register the 1 ore -> 2 crushed macerator recipe for Iridium and should instead let that recipe be picked up by the ore dictionary work (if not register 1 "oreIridium" -> 9 "iridium shards")

**Comment by dshadowwolf** [comment]
and... actual conflict just seems to be that ModernMetals adds a "real" iridium ore, same as TechReborn, and this was causing the issue... I've patched around this (somewhat badly, but it is a fix)
