### ISSUE TITLE
[1.12.2] Rubber Trees Are Super Rare And Don't Respect The Config

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1501]
I was looking for Rubber Trees, but wasn't finding any, so I used /cofh countblocks to see if there even are any. In a 1000x1000 area (specifically a radius of 500 50 500), in 2 worlds nothing was found and in the third only 50 rubber log blocks were found, meaning around 10 trees. In my mind, that is way too rare for something that is required to play the mod. Additionally, I changed the chance for it to 750 and 7500, but it had no effect. For reference, this was tested in a pack with only Tech Reborn and Thermal Expansion.

**Comment by modmuss50** [comment]
I think the config works the other way. 750 means that trees will try to spawn in 1 in 750 chunks so by setting it to 7500 you made them more rare. I don't mind changing the default if required, but its strange how no one else has said they are rare.

**Comment by TheLimePixel** [comment]
Yup, that is how it works.

**Comment by drcrazy** [comment]
Can you provide command you used, please? I'm interested in what block you was searching for.

**Comment by TheLimePixel** [comment]
For the Rubber Log.

**Comment by drcrazy** [comment]
with what meta?

**Comment by TheLimePixel** [comment]
I did not specify it, so 0, I guess

**Comment by modmuss50** [comment]
Ok, instead of changing the numbers as your the first to bring up the issue so I think its ok. (there is a config for you to change if you wish). I have added a rubber plantation to villages. It should spawn at least one in each village, none if your unlucky.

![screen shot 2018-04-30 at 13 36 45](https://user-images.githubusercontent.com/4324090/39427572-2634bf2e-4c7c-11e8-9b98-d1b0d210c6dc.png)

The chest has rubber related loot, tree taps, sap and what not. I hope this is a more interesting solution to your issue.

**Comment by TheLimePixel** [comment]
Huh, cool! Although, I believe I'm the first to bring it up because most people use it in a skyblock or together with IC2. I personally use it in 3 skyblocks.
