### ISSUE TITLE
Fusion Control Computer not using up input

### ISSUE THREAD

**Issue by jalako** [TechReborn/TechReborn#1551]
Okay so as the title suggest the Fusion Control Computer is not using up its fuel - atleast in my case.

I am currently playing on FTB Continuum 1.3.1 (which is currently the latest version).
The version of TechReborn is

_TechReborn-1.12.2-2.15.15.712-universal.jar_

So it happened like this:
I added two hoppers on both sides (so 4 in total) and put Deuterium and Helium3 in them. I then configured the Slots of the Fusion Control Computer. After I saw that it was putting it in I just added that the resulting Heliumplasma would get extracted in a chest and thats it. I went to sleep. The next day the Reactor was still running and did not use up any of the Deuterium and Helium3 cell but ran all the time. It created way more Heliumplasma cells than I even had Helum3 and Deuterium combined. Now looking at it, it is still not using any of the cells.

I was also able to reproduce it by just putting a stack of each into the Computer, it used one, and now it is just running on "air"

http://prntscr.com/jwbky7

This issue is similar to issue #1539 
but as you can see just happens for no apparent reason

If you need any more help or you are not able to reproduce the error don't hesitate to ask me.

**Comment by electromatter** [comment]
I've run into this today too. It seems to be caused by 7db0097d231b0b9cff7b8655bffd9375f23c9aee and 0ae99ebae8b6b30e25db859e1b8c0416b60ce95d together, the first moves the recipe consumption to the start up phase and the second changes the operation of the machine (start up => running => finished => repeat from start up) to just start up => (running => finished => repeat from running).
