### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by mike40376** [TechReborn/TechReborn#1583]
Whenever I try and start my server it crashes on the late stage of loading or crashes a couple minutes after loading, I have no idea why this error is happening I haven't changed anything.
[crash-2018-08-18_20.12.06-server.txt](https://github.com/TechReborn/TechReborn/files/2299950/crash-2018-08-18_20.12.06-server.txt)

**Comment by modmuss50** [comment]
Try deleting idsuData from the world folder, and then starting the server.

**Comment by mike40376** [comment]
I deleted this file and I can no longer join the server, it gives me a Java Exception times out error

**Comment by modmuss50** [comment]
That’s odd, it should regenerate that file. We don’t usually support 1.7.10 but due to this being a server crash I am willing to work on a fix. 

It’s getting quite late now so it may have to wait till tomorrow. But I will build a testing version for you to check that the crash has been fixed.

If possible could you provide the logs for the new crash that has happened after deleting the file.

Thanks

**Comment by mike40376** [comment]
It wasn't a crash, it just did not let me connect to the server after the file was deleted. Before I deleted it I was able to join it for a minute or two before a crash but now it won't even let me connect.

**Comment by modmuss50** [comment]
Ok, after a bit of effort to get it to build again:

https://jenkins.modmuss50.me/job/TeamReborn/job/TechReborn/job/TechReborn-1.7.10/1130/artifact/build/libs/TechReborn-1.7.10-0.7.20.1130-universal.jar

Can you please try this version and let me know if it fixes your issue. You should really consider updating to 1.12.2 as all of these bugs have been fixed.

**Comment by mike40376** [comment]
Thank you that build worked and now everything is running smoothly

**Comment by modmuss50** [comment]
Thanks for testing, I will release this version later today.
