### ISSUE TITLE
Extra items recipes were removed

### ISSUE THREAD

**Issue by EngineerXL** [TechReborn/TechReborn#1615]
MC: 1.12.2
Forge: 65 and also tested 68
TR: 824
Rcore: 335
CraftTweaker: 1.10

Script used: `recipes.remove(<techreborn:lapotroncrystal>);`

Got: cloaking device, chainsaws, drills e.t.c recipes removed

**Comment by Draskh** [comment]
This sounds like this one https://github.com/CraftTweaker/CraftTweaker/issues/627 . Update your version to 4.1.11 and look if it till occur.

Otherwise you should try to use  recipes.removeByRecipeName("RECIPENAMEHERE"); to solve this issue. You can see the name by clicking on an output in JEI. It is called recipe ID.

**Comment by modmuss50** [comment]
yep, doesnt seem like something I can do anything about which is why I was wondering what was up
