### ISSUE TITLE
Rubber Log Needs More Blockstates

### ISSUE THREAD

**Issue by KenyMylankca** [TechReborn/TechReborn#1636]
![asdsa](https://user-images.githubusercontent.com/41585837/49637473-8a38c180-fa16-11e8-9945-5ad553ae51cf.PNG)
you can't place the rubber log just like that jungle log in the picture... can you please fix this? thanks!

**Comment by modmuss50** [comment]
The blocksates that make up the sap spots are using up a good deal of the 16 states. I can look into doing this in 1.12 but it may have to be a 1.13 thing when we have access to more states.

**Comment by coderbot16** [comment]
I was thinking about this issue and I think it could be fixed in 1.12. While the most common method of encoding metadata is bitpacking, where there would be too many blockstates needed (2 bits for sap side, 1 for has sap, and 2 for axis = 5 bits), it is theoretically possible to encode all possible combinations in 15 different states. Instead of bitpacking, you could use arithmetic encoding: there are only 3 axes, and 5 different possibilities for the sap side (4 for each side / 1 for "no side"), leading to 15 combinations, pack able into 4 bits.

Of course, this change would break all worlds like what happened with the leaves metadata changes in the beta days. Still, it is possible.

**Comment by KenyMylankca** [comment]
i would recommend a method that will render sap on the log without the blockstate... but itd be a bit hard to code :D so dunno..

**Comment by modmuss50** [comment]
Breaking worlds is not an option, it will happen in 1.13
