### ISSUE TITLE
[Bug] internal buffers won't drain out of the solar panels

### ISSUE THREAD

**Issue by GlitchOG** [TechReborn/TechReborn#1642]
latest version of tech reborn and reborn core , latest version of forge. 

![2018-12-25_15 44 02](https://user-images.githubusercontent.com/16983936/50426766-50601b80-085c-11e9-8b88-b6bd07ebf45a.png)

![2018-12-25_15 44 06](https://user-images.githubusercontent.com/16983936/50426768-5524cf80-085c-11e9-97ce-c8e2eb9acb39.png)

first image shows how the buffer has 40k rf and second one shows the cable draining but the buffer doesn't even tho my machines are using way more than what the solar panel produces. and yes i changed the amount generated from the solar panel to go along my personal use.

**Comment by coderbot16** [comment]
Solar panels output power at exactly the same rate they generate it. This is simply an implementation detail: in effect, the buffer can only drain when the solar panel is not producing power. What's happening is that the solar panel outputs 40 RF to the wire, and then in the same tick it generates 40 RF, keeping the buffer full. Perhaps there could be an additional configuration option for setting the output rate of the solar panels so that they empty their internal buffer during the day.

**Comment by modmuss50** [comment]
Is this really an issue? I dont see a need for such a config?

**Comment by coderbot16** [comment]
It's honestly not really an issue, and in fact without a WAILA like mod it's not even visible. But, if you were to make it so that the internal buffer could eventually drain even during daytime, with a higher output rate, I was just proposing that the higher rate be made a config option. This is because if someone using TechReborn in an EU environment decided to place an Ultimate Solar Panel configured to generate 512 EU/t right next to their MFSU, and the solar panel all of a sudden started outputting 1024 EU/t with it's secret "boost" rate, it would blow up their machines, which wouldn't be good.

**Comment by modmuss50** [comment]
Closing as its not a major issue. if I had a choice I would not show the internal buffer in walia
