### ISSUE TITLE
[Question] Electric Furnace resets progress on lack of power unlike other machines

### ISSUE THREAD

**Issue by tomdodd4598** [TechReborn/TechReborn#1688]
Hey there!

Just a quick question - is there a reason that the electric furnace's smelting progress [resets](https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/tiles/tier1/TileElectricFurnace.java#L168) on running out of power, while other machines do not?

Thanks in advance.

**Comment by coderbot16** [comment]
Probably because the item
cools down :P

In actuality, this is probably because while most machines extend a common generic machine implementation, electric furnaces have a separate implementation. This is because unlike most machines, furnaces use vanilla recipes, meaning that they are a special case. Therefore it’s probably just an incosistency between furnaces and generic machines.

**Comment by modmuss50** [comment]
yeah, @coderbot16 got it in one, its an easy fix.

**Comment by tomdodd4598** [comment]
Awesome - will save some headaches :P
Thanks!
