### ISSUE TITLE
Industrial electrolyzer auto imput bug

### ISSUE THREAD

**Issue by luigge** [TechReborn/TechReborn#1720]
Hello I am playing on the modpack ftb ultimate reloaded version 1.7.1 minecraft 1.12.2, and the problem is, the industrial electrolyzer is inputing wrong stuff into the "dust" slot like cells or dust that does not have a recipe there how to fix this? there is an itemduct that connects a chest and this machine to send items.

![wrong input](https://user-images.githubusercontent.com/35157185/58393232-39dd0c80-8014-11e9-87d9-e3b14f7b44b1.png)
![wrong input 2](https://user-images.githubusercontent.com/35157185/58393233-39dd0c80-8014-11e9-9b10-4fa1a8054bff.png)

and how can I use the filter input maybe I can use this to fix this issue?

apparently if I put the chest close to the machine the bug don't happen but if I use itemducts to tranport the item, it does.

edit 4? I have tried using the auto input + filter input + blue color for the back side, marked and it seems it is only inputing the correct items but the cells still go to the "dust slot".

**Comment by drcrazy** [comment]
Unfortunately, it is by design. You can't filter cells from input slot due to recipes with cell, for example, water cell -> electrolyzed water cell. There is no NBT filter for slots as for now. 

The only solution I can propose is to have one chest for empty cells and input cells from that chest from a separate side. And input stacks to process (dusts, etc) should input from second chest from other side.

So far you will use 4 sides of this machine:
1) energy
2) input cells
3) input dust
4) output
