### ISSUE TITLE
Fusion Reactor Output yield 

### ISSUE THREAD

**Issue by AHrubik** [TechReborn/TechReborn#1728]
Modpack: Custom FTB Ultimate Reloaded

Tech Reborn version: 1.12.2-2.22.1.979-universal

I'm not sure what the problem is to be honest. The pack by default has the TR set to EU only. I changed that to the RF when I recently discovered there was no good way to extract the energy the fusion reactor can generate. After the change I was still only seeing 8,192 or 32k RF per tick from the reactor even though at size "13" it's generating 600K+ EU/t or 2.4M+ RF/t. The config was set to restrict reactor input to 8192 but output was set to 1,000,000. 

When I changed the reactor **input** rate to 1,000,000 units (to match the configured output) the reactor began outputting 32K EU/t or 132K RF/t. When I changed the input & output rates to 100,000,000 units the reactor was outputting 1,000,000 RF/t. 

As best as I can tell it seems reactor output yield seems to be tied to the input rate in the config file.

**Comment by drcrazy** [comment]
Input and Output rates are not tied. 

As for now config for output rate doing nothing due to output fixed at ~500M RF\t but only if reactor is active, e.g. crafting something.  Besides reactor itself output rate could be limited by duct\wire\whatever is used to extract energy from reactor.

Check here (https://github.com/TechReborn/TechReborn/blob/bdf2587ddcdedf1093d59a973d33160abdd982df/src/main/java/techreborn/tiles/fusionReactor/TileFusionControlComputer.java#L314) for more details.
