### ISSUE TITLE
[Suggestion] Add higher tiers of solar panels

### ISSUE THREAD

**Issue by Vintschente** [TechReborn/TechReborn#1830]
The current max solar panels are rather mid game. Adding 3 or 4 more tiers (16K FE, 64K FE, 256K FE, 1024K FE) each requiring more and more end game like resources (please no tons of nether stars but maybe a dragon egg included at one point or one nether star) and alloys that can only be crafted with more and more upgraded TR machines. I realized while playing that I really wanted to continue using the solar panels but had to switch to another mod to get enough power.

Best Regards

**Comment by coderbot16** [comment]
Generating huge amounts of power is the purpose of a fusion reactor. The max tier TR solars are way unrealistic (and quite powerful) as is, and passive power generation is generally not balanced at these scales. This issue is the fault of powercreep in other mods.

**Comment by Vintschente** [comment]
I get your point but the fusion reactor is still way higher tier in energy production than even a 1024K FE solar panel. After all, a solar panel is nothing more than an automated energy production block compressed into one block working only during daytime. A fusion reactor can be automated as well, couldn't it?

**Comment by coderbot16** [comment]
The first part isn't really true. The smallest size fusion reactor, which still requires thousands of ingots of iron, copper, tin, etc, not to mention tons of iridium, only outputs 128K FE/t. The power generation is specifically designed so that the fusion reactor will comfortably sit above all other options in the mod. Adding a lot of OP solars defeats this purpose.

In addition, the automation requirement cannot be written off. It takes many centrifuges to sustain a reactor, and many pipes to route the products and inputs to each step of the water -> deuterium/tritium process. This sits on a completely different level than just plopping down a passive generator and letting it do its thing.

A fusion reactor is still free renewable energy, it just takes effort to automate and more complexity than just a solar panel. Adding these high tier solar panels, aside from messing with TR's own progression, also serves to continue the cycle of powercreep that would make an addition like this thinkable in the first place.

**Comment by Vintschente** [comment]
Alright I get your points and have to accept it I guess. Atleast one higher tier like 16k FE would be fine.

But can we please stay away from the term power creep here? This has nothing to do with it. Crafting items or blocks that are powerful with expensive resources isn't - crafting them with comparable cheap resources is. Killing everyone in one hit who doesn't wear draconic vs. the chaos guardian is. Making the chaos chicken in stoneblock 2 immune to the Sword of the Cosmos is. This here just isn't.

**Comment by Chocohead** [comment]
Whilst power creep is indeed not really the right description, power inflation probably is. 

Adding ever more powerful power generators will only drive the demand for power up as it becomes relatively easier to produce. Either late game power generation becomes irrelevant once you can pay your way to make enough solars (as they after all have no maintenance cost once made) or the power demand has to pick up to justify making a fusion reactor. Having the fusion reactor at all suggests the first option isn't a likely aim at which point you're left with the second. Which then feeds the cycle that the other existing generators don't seem to output enough and everything has shifted upwards.

Both creep and inflation will result in the same outcome of power devaluing, the difference is creep acts only from what other mods add whilst inflation can act from both other mods and TR's own tech tree.

**Comment by drcrazy** [comment]
You can build array from several solar panels to match reactor output.
