### ISSUE TITLE
[1.14.4] Fix Cable/Machines Energy Bug 

### ISSUE THREAD

**Issue by AndaPlays** [TechReborn/TechReborn#1858]
Cables don't transmit energy (sometimes), Machines too.
After restarting Minecraft it is fixed.

**Comment by fjgreer** [comment]
Cables don't work for me at all, even after many restarts.
Power does transfer from block to block.  IE.  plopping a creative solar panel next to an MFSU.  Just not via cables.

Game Version: 1.14.4
Fabric Version:  0.6.3-build.167

Mods:
  [✔️] always-drop-loot-3.6.0+mc1.14.4
  [✔️] appleskin-mc1.14-fabric-1.0.7
  [✔️] beach-slimes-1.3.0+mc1.14.4
  [✔️] betterthanmending-fabric-1.0.0
  [✔️] buffer-1.14.4-1.8.3
  [✔️] clothesline-fabric-0.1.2-all
  [✔️] composable-automation-0.6.0+mc1.14.4
  [✔️] diggusmaximus-1.0.6
  [✔️] fabric-api-0.4.0+build.240-1.14
  [✔️] fabric-language-kotlin-1.3.50+build.1
  [✔️] fabricmod_VoxelMap-1.9.13_for_1.14.4
  [✔️] foamfix-0.10.7-1.12.2
  [✔️] Harvest-1.14-fabric-1.0.4
  [✔️] Hwyla-fabric-1.14.2-1.9.17-66
  [✔️] InventorySorter-1.5.7
  [✔️] lead-villagers-1.2.0+mc1.14.4
  [✔️] LightOverlay-3.5
  [✔️] modmenu-1.7.14.1.14.4+build.126
  [✔️] nbtcrafting-1.2.4+1.14.4
  [✔️] optifabric-0.5.2
  [✔️] OptiFine_1.14.4_HD_U_F3
  [✔️] orderly-1.1.2+build.19
  [✔️] proletarian-0.10.2+mc1.14.4
  [✔️] RebornCore-1.14.4-4.0.19+build.187
  [✔️] RoughlyEnoughItems-3.1.5+build.31
  [✔️] simpleteleporters-2.2.0
  [✔️] SimpleVoidWorld-3.0.0
  [✔️] SoulShards-fabric-1.14.4-1.0.11-13
  [✔️] stockpile-1.1.2+1.14.4
  [✔️] tdnf-1.5.57+1.14.4
  [✔️] TechReborn-1.14.4-3.0.17+build.250
  [✔️] Tumble+Dryer-1.1
  [✔️] UnitedConveyors-0.0.1
  [✔️] vanillaexcavators-1.0.2
  [✔️] vanilla-hammers-1.6.3
  [✔️] yabm-2.0.1

I saw no warnings or errors in the log pertaining to techreborn, but I'll attach them anyway.
[minecraft-log-20191021-1.txt](https://github.com/TechReborn/TechReborn/files/3749119/minecraft-log-20191021-1.txt)

**Comment by Kjasi** [comment]
I, too, am having this issue. It's showing up on my server. Block-to-Block, power works fine. Cables do not seem to transfer power. (Is there a cable monitoring tool to see how much power is being transmitted along the cable being looked at/inspected?)

I saw an issue that said that cables didn't transfer power from batbox to machine, but worked batbox-to-batbox. This is no longer the case. Cables do NOT transfer power between batboxes. I tested all the cables, and none of them seems to be transferring any power.

Mods on the Server:
- BiomesOPlenty-1.14.4-9.0.0.254
- expandedstorage-3.6.29+1.14.4
- fabric-api-0.4.0+build.240-1.14
- InventorySorter-1.5.7
- RebornCore-1.14.4-4.0.19.build.187
- TechReborn-1.14.4-3.0.17.build.250
- terrestria-1.0.11+build.40
- traverse-2.0.8+build.26

Additional Client mods:
- optifabric-0.5.2
- OptiFine_1.14.4_HD_U_F3
- RoughlyEnoughItems-3.1.5+build.31

Since both I and @fjgreer both use InventorySorter-1.5.7, (only mod we both used, other than TechReborn) I tried a single-player mode with that disabled. Same results.

**Comment by DbpGaming** [comment]
how are you loading a forge mod (biomes o plenty) and a fabric mod(tech reborn) together? i doubt that could be helping the issue
