### ISSUE TITLE
marble have 2 recepies in grinder

### ISSUE THREAD

**Issue by lxn12596** [TechReborn/TechReborn#1886]
marble (from quark mod) have 2 recepies in grinder
one to sand
another to marble dust
now it can't be grind to  marble dust

**Comment by voidsong-dragonfly** [comment]
Is it in the OreDictionary for Stone?

**Comment by lxn12596** [comment]
yes

**Comment by voidsong-dragonfly** [comment]
That would be why, and it'd need to be removed from the stone OD to work.

**Comment by drcrazy** [comment]
This issue could be solved in two ways:
1) TR should not support ore dictionary for cobblestone to sand recipe. This will lead to a lot of stones from other modes being not grindable
2) Fix your mod pack and remove marble being oredicted to cobblestone.

I suggest to follow the second way because of much less unpredictable impact on compatibility with a lot of other mods.
