### ISSUE TITLE
[1.15pre6] Glass fiber seeming better than Superconductor?

### ISSUE THREAD

**Issue by zeflap** [TechReborn/TechReborn#1904]
The setup for both is the same, and the output from the matterfab is at the same speed for both.
![2019-12-10_10 04 55](https://user-images.githubusercontent.com/4191012/70507305-beb4f100-1b34-11ea-9c59-ed2aed3ba21c.png)
Yet, the glass fiber one is rock solid at 32m on the aesu
![1575965104](https://user-images.githubusercontent.com/4191012/70507392-eb690880-1b34-11ea-8ae8-3159dbf129b3.png)
while the superconductor ramps wildly between 0 and 2kEU
![1575965115](https://user-images.githubusercontent.com/4191012/70507453-12273f00-1b35-11ea-8843-d952bd91488a.png)

In a setup with a constantly-being-filled AESU feeding a blast furnace, 4x overclocked, glass fiber could handle the power draw yet superconductors were struggling heavily.
Baffling, ain't it?

**Comment by drcrazy** [comment]
This is due to cables being dumb. Every tick cable tries to send energy to any other block entity which can accept it. Thus resulting in ping pong of energy between each cable block entity. Glass fiber has lower internal buffer thus as soon as it get 32k energy it can't accept anymore while superconductor can buffer Java max integer \ 4. 

Possible solution is to wait till all superconductor cables fill in internal buffer which is quite long, unfortunately.
