### ISSUE TITLE
Use bronze plates instead of brass plates for crafting the wire mill0

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#1938]
**Is your feature request related to a problem? Please describe.**
The wire mill is a low tier machine that has the potential to save quite a bit on materials.  Right now it needs brass plates to be crafted.  Brass needs zinc, which can only be obtained using either the industrial electrolyzer or the industrial grinder.  

**Describe the solution you'd like**
I'd like for the wire mill crafting recipe to be changed to accept bronze plates instead of brass plates.

**Describe alternatives you've considered**
I considered other materials.  Gating the wire mill behind iron plates might be too easy.  With bronze plates, the wire mill is gated behind the alloy smelter.

**Additional context**
The mixed metal ingot has a crafting recipe with bronze or brass.  This suggests the materials are somewhat interchangeable.

**Comment by drcrazy** [comment]
This is a point for wire mill and for assembling machine. 
You either spend more using crafting table recipes or less using machine. Machine in this case will be gated behind some progression in order to not to make it a nobrain option.

Similar approach for industrial grinder, for example. You can still grind your ores in usual grinder for standard output or grind in industrial grinder for additional output. Industrial grinder requires some mats and some other machines thus kind of gated behind these mats \ machines. 

You can still change recipe for wire mill using data pack or LibCD.
