### ISSUE TITLE
1.15 lastest built No Battery Recipe 

### ISSUE THREAD

**Issue by HenryChelt** [TechReborn/TechReborn#1967]
**Describe the bug**
No Battery recipe Im following the recipe

**Screenshots**
![Untitled2](https://user-images.githubusercontent.com/59744162/72179749-86c3f680-33dd-11ea-813b-3d12d5966a4b.png)
![Untitled](https://user-images.githubusercontent.com/59744162/72179755-89bee700-33dd-11ea-8110-ecd1fa775d02.png)

**Comment by vhd** [comment]
Are you sure it is latest build?
Can you provide your mod list/versions?
Anyway, here is my test. Recipe was changed, it's now lead instead of tin.
TechReborn-1.15-3.2.1+build.107
<img width="966" alt="Снимок экрана 2020-01-10 в 22 26 39" src="https://user-images.githubusercontent.com/487056/72184123-5b023a00-33f8-11ea-9aa6-d0dab1086df5.png">

**Comment by drcrazy** [comment]
Wiki fixed. Thank you!
