### ISSUE TITLE
Lapotronic Orbpack put in AESU charging will gone when u leave for a while

### ISSUE THREAD

**Issue by jimahy7687** [TechReborn/TechReborn#2018]
**Describe the bug**
Lapotronic Orbpack put in AESU charging will gone when u leave for a while

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by JessiAuro** [comment]
I have been unable to reproduce this in a test world. I was able to charge an orbpack to full in an AESU and left the game running for about four hours. I tested all other energy storage blocks without any issue either.

Sometimes items can "disappear" due to some sort of client-side bug, I would restart the game and make sure it is still missing.

**Comment by JessiAuro** [comment]
I now have been able to reproduce it. It appears to be related to the chunk loading as it disappears once I opened the world later.

My orbpacks in all the other energy storage blocks are still present.
