### ISSUE TITLE
Add Rubber Sign and Boat

### ISSUE THREAD

**Issue by saltyseadoggo** [TechReborn/TechReborn#2277]
**Is your feature request related to a problem? Please describe.**
There is no Rubber Sign or Rubber Boat, making this mod's Rubber wood type not match vanilla wood types in what can be made with it.

**Describe the solution you'd like**
Add a Rubber Sign and Rubber Boat.

**Comment by drcrazy** [comment]
Won't fix. 

Vanilla doesn't provide easy way to extend neither BoatEntity nor bunch of Sign related classes compare to slabs, stairs, etc. 
We have two options  - almost full rewrite of vanilla classes or wait if there will be changes in extensibility in 1.17 and later. 

I've choose second option due to a lot of efforts to be spend on cosmetic stuff. 

Feel free to re-open when MC 1.17 will be released.

**Comment by saltyseadoggo** [comment]
Interesting. Given that TerraformersMC was able to tie into the boat and sign classes with their Terraform library https://github.com/TerraformersMC/Terraform, I had thought that this was simpler than it is. Would it be possible to ask for their permission to use that library to make this work?

**Comment by drcrazy** [comment]
Terraform replicated vanilla stuff. 

For example boat: 
![image](https://user-images.githubusercontent.com/1382352/99842693-629a7f80-2b81-11eb-80c4-85decf42989a.png)

**Comment by saltyseadoggo** [comment]
Ah, gotcha. Well, you could still ask to use it to make your job easier.

**Comment by haykam821** [comment]
Is using Terraform still an option for Tech Reborn to have rubber signs and boats?

**Comment by Ayutac** [comment]
Doesn't look like me much has changed regarding the boat in Vanilla. Could be doable though

**Comment by Ayutac** [comment]
Nope, still not viable
