### ISSUE TITLE
Iron and copper dont work in grinder

### ISSUE THREAD

**Issue by SaltyDude07** [TechReborn/TechReborn#2422]
If you try and grind iron and copper in the grinder, it wont work. I think it's because it's not marked as more its raw iron and raw  #copper.

**Comment by drcrazy** [comment]
Is it about iron ore or raw iron or iron ingot?

**Comment by drcrazy** [comment]
Iron ore grinds fine.

![image](https://user-images.githubusercontent.com/1382352/125870084-cf5de267-7c78-4f7a-92d5-991810bbf28c.png)

**Comment by arslan2012** [comment]
@drcrazy [In 1.17 you don't get ores, mining iron ore drops raw iron, you need a silk touch pickaxe to get iron ore now.](https://minecraft.fandom.com/wiki/Raw_Iron)

That's why I think the `XXX ore -> 2 XXX dust` recipe should be replaced by `raw XXX -> 2 XXX dust`.

the `XXX ore -> 2 raw XXX` is redundent。

This issue should be reopened.

**Comment by Ayutac** [comment]
Iron dust is gone already. Long live Raw Iron!

**Comment by arslan2012** [comment]
what I want to know is with iron dust gone and iron ore unminable, how do we go about the ore duplicating now? @Ayutac

**Comment by Ayutac** [comment]
Fortune enchantment. Ore duplication is now part of Vanilla Minecraft.

**Comment by thennothinghappened** [comment]
disappointing that this is basically the ic2 macerator yet it doesn't fill the same role that it should in 1.17
