### ISSUE TITLE
LESU loose load

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [TechReborn/TechReborn#2424]
MC 1.17
fabric-loader-0.11.3-1.17
TechReborn-5.0.3-beta+build.55.jar

Builded a LESu with 128 Blocks
load with charged lapo.energy.orb
load up 10 10 meg
quit world
load world

lesu shows correct value ( in WTHIT)
as soon the Quantum ARMOR is loaded ( recogniced), means FOV changes
LESU fall back to 1 Meg

regards
daniel

**Comment by mnsnownutt** [comment]
Can confirm this happens.  

MC 1.17
TechReborn-5.0.3-beta+build.55.jar
fabric-api-0.36.0+1.17

Any power over 1M stored in a LESU mulit-block will be deleted/reset/lost upon logging off.  Screenshots showing charge above 1M, then exactly 1M after logging off and back on.

![2021-07-24_06 51 57](https://user-images.githubusercontent.com/31514693/126867685-1e5f18ee-ad7b-48ff-be83-5910c6a8bcd6.png)
![2021-07-24_06 52 37](https://user-images.githubusercontent.com/31514693/126867691-c965eeb4-a900-429b-b0c2-365a89822005.png)

**Comment by mopsy14** [comment]
Just after I created an issue I found out it already exists. But I have given one possible explanation:
I think this happens because, when the server starts the LESU controller is identified as a block with 1M energy and since the saved data is for example 5M energy, the energy will be set to the max (1M). After that, the LESU Storage will be added and the max will be set to for example 6M.
And I can also confirm this bug.

**Comment by mnsnownutt** [comment]
I was in a single player environment when I experienced the issue.

**Comment by mopsy14** [comment]
I was in a server environment, so that can't be the problem.

**Comment by xanthian** [comment]
I can confirm this still occurs in 1.18.1.

Log out with 40m stored in LESU
restart server
Log back in with only 1m stored.

**Comment by OberstK** [comment]
I can confirm that this happens for me as well on: 

MC 1.19 on a server and in singleplayer
TechReborn version 5.3.2
fabric api 0.58.0+1.19
