### ISSUE TITLE
For some reason, I can't craft anything from the Tech Reborn mod.

### ISSUE THREAD

**Issue by coolguy743** [TechReborn/TechReborn#2466]
Whenever I try to craft an item from the Tech Reborn mod, the item simply doesn't craft.

**Comment by drcrazy** [comment]
Can't reproduce. 

![image](https://user-images.githubusercontent.com/1382352/129209052-6ceb7543-197e-421d-9303-f6acacb0282c.png)

**Comment by Derpford** [comment]
This bug is present in 1.18. I can't craft copper cables or batteries.

![2021-12-04_23 04 53](https://user-images.githubusercontent.com/10187719/144737137-0f26a693-c785-420a-9150-e40c72465cff.png)
![2021-12-04_23 06 14](https://user-images.githubusercontent.com/10187719/144737161-9c93e7d6-8a23-4ddf-b282-cee395e395a3.png)

The recipes show up in REI, oddly enough.

![2021-12-04_23 06 39](https://user-images.githubusercontent.com/10187719/144737173-7c298025-b078-4775-883c-a6eac23a33a7.png)
![2021-12-04_23 06 31](https://user-images.githubusercontent.com/10187719/144737176-0e93c947-c5fc-4158-bb11-43f8d48081cb.png)

**Comment by Derpford** [comment]
Update: I have traced this recipe issue and similar recipe problems back to an interaction with Just Copper Tools. I've opened an issue [here](https://github.com/MaximPixel/Just-Copper-Tools/issues/2).
