### ISSUE TITLE
Itemstack issue

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#26]
When something is crafting and the output is taken out the stack size of the recipe output is set to 0.

It looks like its an issue with the item shift clicking code (currently buildcrafts)

**Comment by modmuss50** [comment]
Also don't fell bad if you want to say my code is wrong and I should redo it all or something. That is how people learn.

**Comment by joflashstudios** [comment]
This sort of thing is why you generally don't want to just publicly expose lists like this. You never can tell what is changing it from where when, because there's no code managing access control. A singleton class with add, lookup, delete, etc. functions might help avoid these things in the future.

**Comment by modmuss50** [comment]
Ok thanks, I will try adding that in.
