### ISSUE TITLE
cant craft vanilla recipes without rubber wood on server

### ISSUE THREAD

**Issue by darkcatsenpai** [TechReborn/TechReborn#2674]
Whenever i tried to play on a server and craft a crafting table, it doesn't work.

I took four oak wood planks and put them in order, but i couldn't get the crafting table.
I tried it with rubber tree planks and it works just fine.

![2021-12-22_20 09 26](https://user-images.githubusercontent.com/76266386/147143185-ccf82009-4f0f-4294-8624-f00dc3bedf4b.png)

 - Minecraft: 1.17
 - Mod Loader: fabric 0.12.12
 - Mod Version: TechReborn-5.0.3-beta+build.55.jar

Well, it works fine in Singleplayer, but Multiplayer is broken and there aren't any logs.

It could have compatibility issues with BetterNether

**Comment by Ayutac** [comment]
Don't see why TR would create this issue. 

https://github.com/TechReborn/TechReborn/blob/1.18/src/main/resources/data/minecraft/tags/blocks/planks.json

there rubber planks are added. The crafting table recipe works with any planks. I think this isn't a TR bug, but a bug TR's rubber planks circumvent successfully

EDIT: on the other hand I cannot see at first glance BetterNether to properly add their woods to the wood tag, but maybe they didn't do it within a file. Hrm...

**Comment by xanthian** [comment]
What other mods are installed?
is this a modpack

**Comment by StellarWind22** [comment]
![image](https://user-images.githubusercontent.com/20616317/147838236-5baec9c7-8096-466d-ac01-cebc786ee31c.png)

I'm having this same issue in 1.15.2 with version 3.3.11+build.224. In my development environment.

Here is my list of mods:
- Fabric API
- TechReborn
- RebornCore
- FabricShieldLib
- BasicShields  

It's really strange because both shield mods don't touch the minecraft:planks tag at all.

**Comment by xanthian** [comment]
Does this still occur in 1.18?

**Comment by Baaanfy** [comment]
It works fine in 1.18.1
