### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Ecorous** [TechReborn/TechReborn#2679]
Add Modrinth Support

**Comment by modmuss50** [comment]
Not just yet, curseforge is the main place to download TR from. Sorry.

**Comment by JustAnOkapi** [comment]
+1

**Comment by vaporvee** [comment]
@modmuss50 is there a explaination for this? in newer issues you just answer with "no". Wan't to release my mod and modpack on modrinth is there something to know?

**Comment by Dragon-Seeker** [comment]
Frankly kinda confused how #3365 uses this as the current answer, as 3 Years have passe,d and I agree modrinth could be doing better in areas, but based on the fact that FAPI, Modmenu, and Fabric Language Kotlin are projects run by modmuss with considerable downloads you would think it best to at least look at having techreborn on modrinth in some capacity or have a discussion about this rather than a flat 'no'.
