### ISSUE TITLE
Remove Digital Chest 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#284]
Digital Chest was added after the version we are remaking Quantum Chest is still fine

**Comment by asiekierka** [comment]
Is it really a bug to add new things?

**Comment by joflashstudios** [comment]
I really agree with @asiekierka - I think the goal shouldn't so much be to re-implement a specific version and feature-set of GregTech as much as it is to take GregTech and use it as a basis/inspiration for a mod that's fun to play. I don't think you should really make ANY design decisions just based on what was or wasn't in 2.79c (or whatever version.)

If there's a design/balance/whatever reason to not include the digital chest, then sure. Add or remove things to your heart's content. I just want to say I think it's best when game design comes before a strict adherence to the changelogs of an old mod.

**Comment by Xen1290** [comment]
I've said this for weeks...

**Comment by modmuss50** [comment]
So you saying take the good things from GT and then merge it to make it work great with modern minecraft?

**Comment by Xen1290** [comment]
For me, re-implement all GregTech(2-3)things and then add other, like BluePower did

**Comment by modmuss50** [comment]
I need a solid list of things that need doing, not just a bunch of random github issues. I will come up with a place where I can see what needs doing.

**Comment by joflashstudios** [comment]
What I was talking about isn't even so much about original content, thought that is also good if it's creative and fun to play.

What I was saying was that I think it is pointlessly restrictive to say that you're essentially re-implementing a specific release of GT. My original understanding of the project was that you were trying to take all of the fun and general flavor of GT pre-GT5 where things changed dramatically, and make it work for 1.7.10. 

Within that design framework you have the flexibility to pick and choose features - do you like the way fusion reactors were done later in GT 4, but prefer the way the industrial blast furnace worked in GT 2? There's no reason to limit yourself to either 4 or 2, as long as the features aren't contradictory or otherwise necessarily mutually exclusive.

**Comment by TheQuantumGeneral** [comment]
I agree with the points made by Joflashstudios
