### ISSUE TITLE
(Basic) Drill doesn't break torches, especially not instantly

### ISSUE THREAD

**Issue by Ayutac** [TechReborn/TechReborn#2856]
MC 1.18.2
TR 5.2.0-beta.2

Other mods are present, but I doubt they are responsible for this

**Comment by Ayutac** [comment]
Still exits in TR 5.3.4 standalone. Holds for torches, soulfire torches, redstone torches. Doesn't for e.g. item frame.

**Comment by xanthian** [comment]
Not just torches
any tree, cactus, dead bush.
can understand trees and cactus but dead bush and torches are insta break no matter what is held

**Comment by xanthian** [comment]
Export of tags applied to tool, no difference between them 🤷‍♂️


![image](https://user-images.githubusercontent.com/7688001/202927891-193cd988-d06c-497b-9ea6-3cf07580afe5.png)
![image](https://user-images.githubusercontent.com/7688001/202928073-ed48e922-3138-4d1e-b8e8-edd0209839f9.png)
![image](https://user-images.githubusercontent.com/7688001/202928081-c4cf8ec0-8dd7-4f64-ac56-f1c8bd60f18c.png)

**Comment by KonSola5** [comment]
https://github.com/TechReborn/TechReborn/blob/6622285fe978c7a73e2d01e7c3977d266b202596/src/main/java/techreborn/events/ModRegistry.java#L205

Constructor for reference:

https://github.com/TechReborn/TechReborn/blob/af1159f573ea7a08a5577fbd0757d3ae2e241919/src/main/java/techreborn/items/tool/DrillItem.java#L55-L64

The unpowered breaking speed multiplier is literally NEGATIVE.

And since Torches don't need a tool, the negative mining speed is applied to them.

**Comment by KonSola5** [comment]
https://github.com/TechReborn/TechReborn/blob/af1159f573ea7a08a5577fbd0757d3ae2e241919/src/main/java/techreborn/items/tool/DrillItem.java#L67-L79

Special highlight to the `Math.min` function.
-5 is obviously smaller than 6, so -5 is the mining speed for non-effective blocks.
