### ISSUE TITLE
Beta 3 crashes on launch beta 2 does not

### ISSUE THREAD

**Issue by netcore10** [TechReborn/TechReborn#2930]
**Describe the bug**
Crash on launch.

**Steps to Reproduce**
I don't really know

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[Log](https://hastebin.skyra.pw/eseloxunig.nestedtext)
**Additional context**
Probably a conflict somewhere.

**Comment by Ayutac** [comment]
are you on most recent Fabric loader?

I had a few random crashes as well, with random exit codes, but starting it again worked. I'm on Loader 14.0 though

**Comment by Ayutac** [comment]
No wait, you are on Minecraft 1.18? We are currently on 1.18.2.

**Comment by netcore10** [comment]
1.18.2 , not quite the latest fabric. lemme test

**Comment by netcore10** [comment]
nope still crashes.

**Comment by Ayutac** [comment]
Only TR and fabric and it crashes?

**Comment by modmuss50** [comment]
Looking at the log this has nothing to do with TechReborn:

`java.lang.NullPointerException: Cannot invoke "com.tom.cpm.client.CustomPlayerModelsClient.initGui(net.minecraft.class_437)" because "com.tom.cpm.client.CustomPlayerModelsClient.INSTANCE" is null`

It seems to be an issue with your custom player models mod.

**Comment by netcore10** [comment]
It's actually advanced reborn addon! It hasn't followed in polarity with your new updates.
