### ISSUE TITLE
Recipe tags instead of id recipes

### ISSUE THREAD

**Issue by StockiesLad** [TechReborn/TechReborn#2941]
Very simple:
Tech reborn recipes don't use tags. This causes compat issues.

**Comment by Ayutac** [comment]
thats not true, tags are used. there are just some recipes where it was forgotten. You can help by listing them

**Comment by StockiesLad** [comment]
Metal block recipes such as metal stairs, slabs, etc. I haven't found any on machines thus far.

**Comment by Ayutac** [comment]
But this is by design? Blocks from other mods look different. If they were to introduce their own slabs etc. they would use the same recipe pattern. How would MC then tell the two apart?
This particular use case is an issue for modpack authors I believe.

Also all metal recipes can be accessed via Stonecutter.

Any other recipes where tags appear to be missing?

**Comment by Ayutac** [comment]
No reply after 4 weeks
