### ISSUE TITLE
GreenHouse Controller harvesting experience seeds instead of Bottles o Enchanting like it should from Amethyst Imbuement

### ISSUE THREAD

**Issue by nixord** [TechReborn/TechReborn#3123]
**Describe the bug**
House Controller harvesting experience seeds instead of Bottles o Enchanting like it should from Amethyst Imbuement.

**Steps to Reproduce**
- First Step: put down a Greenhouse controller near these bushes.
- Second Step: Power it to make it work.

**Environment**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric

**Logs**
https://paste.ee/p/E64m0

**Comment by Ayutac** [comment]
That's a lot of mods. Can you reduce it to the necessary ones? And what bushes?

**Comment by fragtastic** [comment]
The mod is `Amethyst Imbuement`.
The `Greenhouse Controller` is harvesting `Experience Bush Seeds` from the `Experience Bush`, instead of `Bottle o' Enchanting`.

https://modrinth.com/mod/amethyst-imbuement
https://amethyst-imbuement.fandom.com/wiki/Experience_Bush_Seed
https://amethyst-imbuement.fandom.com/wiki/Experience_Bush

**Comment by drcrazy** [comment]
Experience Bush doesn't drop Bottle o'Enchanting when harvested like vanilla crops. Only seeds. 
Amethyst Imbuement used SweetBerryBush as a parent class. This is why Greenhouse controller can process it. 
But changes behavior to not match behavior of SweetBerryBush. 

There is nothing we can do without making compat code specifically for Amethyst Imbuement. 
On the other hand, they can either descend from different Vanilla class or behave similarly as Vanilla Bush.
