### ISSUE TITLE
bronze ingot isnt tagged

### ISSUE THREAD

**Issue by danilwhale** [TechReborn/TechReborn#3189]
bronze ingot isnt tagged as `c:bronze_ingots` and because of that, for example, mixed alloy ingot craft contain empty line, wrench is uncraftable

![image](https://github.com/TechReborn/TechReborn/assets/61111955/3a1ed563-8884-42b4-ab26-a2929e74b14d)
![image](https://github.com/TechReborn/TechReborn/assets/61111955/2185b40a-15b9-4077-9ff8-beb000d946ae)
![image](https://github.com/TechReborn/TechReborn/assets/61111955/08505c46-4b8a-40da-94c5-7e7e25be4877)

minecraft: 1.20.1
mod loader: fabric
mod version: 5.8.7

**Comment by xanthian** [comment]
Just created a fresh instance with TR 5.8.7 installed on 1.20.1
Only other mod installed is REI to check the tags.

Looking within the jar file i can see the tag is present 
TechReborn-5.8.7.jar\data\c\tags\items\
```json
{
  "replace": false,
  "values": [
    "techreborn:bronze_ingot"
  ]
}
```

and ingame
![image](https://github.com/TechReborn/TechReborn/assets/7688001/80734e4a-910e-4f2d-90ef-3bec896f22c6)
![image](https://github.com/TechReborn/TechReborn/assets/7688001/448e6031-27fc-4cc3-a985-8ed330bfd75b)


It would suggest to me that something is wrong your end, eg Modpack related.

**Comment by SMN47** [comment]
Greetings. I'm currently updating the mods on my 1.19.2 modpack (240+ mods). At some point I encountered an absolutely identical problem, and I managed to pinpoint the mod that causes this behavior. To my surprise it turned out to be an iron bookshelves. Version 1.1.2 works well, but after updating it to version 1.2.3, bronze ingot tag magically disappear - and hello, bunchh of bronze armor from nothing. I'm not finished yet, but about this one moment i am certain. Perhaps this clue can help in the future to fully clarify the reasons for such strange behavior/dependence.

TR 5.4.0, EMI 1.0.23, Sodium +addons, Fabric API 0.76.1

**Comment by xanthian** [comment]
version=1.19.2 - 1.2.3 of Iron Bookshelves has 
c/tags/items/bronze_ingots.json

```json
{
  "replace": false,
  "values": [
    "ingotcraft:bronze_ingot"
  ]
}
```

which shouldn't cause conflicts, without testing, i'm not sure its that.
You are correct in that this was added in version 1.2.3 though

**Comment by drcrazy** [comment]
Can't reproduce in dev env with TR only. 

We have bronze_ingot tagged.

![image](https://github.com/TechReborn/TechReborn/assets/1382352/1e3504e8-e3ad-451f-8937-3bed9cbc143c)
