### ISSUE TITLE
reconsider closing #3333

### ISSUE THREAD

**Issue by ix0rai** [TechReborn/TechReborn#3336]
hi! i believe that closing #3333 without discussion is unfair, for a couple reasons:
- it does not create additional maintenance burden, being a simple matter of two API calls to fix the issue. the argument of not supporting other platforms doesn't make any sense when you're not the one undertaking the work to fix issues.
- it's an idiomatic usage of an underused API. this is exactly the way that loader API is intended to be used, and provides a helpful example for those looking to call it in the future.

thank you!

**Comment by ix0rai** [comment]
as i said in #3333, this isn't a difference between floader and qloader -- it's a mappings issue when using a different intermediary. you're misunderstanding the issue, it's a problem when using any runtime mappings besides intermediary on any loader. i'm disappointed in how you've handled this, i simply offered a fix in good faith for an issue.

**Comment by modmuss50** [comment]
I fully understand the problem here, I'm not worried about that.

If I want to support another loader I will want to make sure that the mod is tested and works as expected, its possible there might be other issues beyond this that we dont know about. I appreciate the time you have put into this, but please also appreciate the time I have to waste supporting stuff I have no clue or intrest in. I know that connector exists, however they aim to fix the issues on their end this arragement works well for me as I dont need to put any effort in, consider doing something similar.

It doesnt happen so much with TR but recently I have spent mutliple hours looking into mapping [issues ](https://github.com/FabricMC/fabric-loom/pull/1190) in loom that turned out to be becuase of these same quilt mappings. I have no time or patience left for supporting it, I have enough to keep me busy with projects that actually concern me. I also doubt TR is the only mod doing something like this.

I get that some quilt folk dont like what I do, but please understand my side of things and leave me out of it. Feel free to post this on your drama discord servers as I assume you wanted this kind of reaction out of me. Well done you got it, now please leave me alone.
