### ISSUE TITLE
Cupronickel not possible to create - Alloy Furnace recipe issue and bronze created instead

### ISSUE THREAD

**Issue by Chelkin** [TechReborn/TechReborn#444]
Unable to craft cupronickel via Iron Alloy Furnace.  On adding Copper and Nickel to the Iron Alloy Furnace it creates 4x bronze instead of 2x cupronickel.  Attempted on latest version of mod for 1.7.10 and 1.9 (with no other mods) as of 29/3/16 and issue is the same.  Unable to progress further through tech as Cupronickel coils are required for blast furnace and further tech progression.

Currently playing 1.7.10, only tried 1.9 to see if problem was unique to 1.7.10. Any fix/work around?

Thanks,

Chelkin

**Comment by mystise** [comment]
Can confirm, iron alloy furnace produces bronze and only consumes 1 copper and one tin, while the electric alloy furnace produces cupronickel just fine. The iron alloy furnace also stopped producing after one run, the progress bar stuck at 0 (or 1 if you don't leave the GUI), presumably because it is checking for the correct recipe before starting, but then producing incorrect output items.

![2016-03-28_20 15 00](https://cloud.githubusercontent.com/assets/246232/14096173/d6afaf4c-f523-11e5-93b7-d1d95ce10a15.png)
![2016-03-28_20 15 25](https://cloud.githubusercontent.com/assets/246232/14096174/d6be2c16-f523-11e5-9379-bc3c5559d73d.png)

**Comment by modmuss50** [comment]
This will only be fixed in 1.9

**Comment by gigabit101** [comment]
@modmuss50 do you know why this is happening ?

**Comment by gigabit101** [comment]
dont the use the same recipe handler
