### ISSUE TITLE
[1.9] Power generation/usage

### ISSUE THREAD

**Issue by Inari-Whitebear** [TechReborn/TechReborn#564]
So, maybe I'm in the wrong on this, but it seems the generation/usage is kind of wonky?

Like the basic machines without any upgrades can't seem to run on a copper cable properly. Even the Thermal Generator I made used 2 buckets of lava and only had the extractor process 6 items during that time... Just seems like there is either too much usage or too little production. The 4k batbox is zapped empty by the extractor in a second too :/

**Comment by Inari-Whitebear** [comment]
It seems the furnace uses a normal amount of electricity though

**Comment by xannor** [comment]
I was curious about this as well so I dug through the code and here is my findings...
The extractor  recipe is listed as 20 eu a tick for 400 ticks. This is 8000 eu per operation.
The generator only generates 10 eu a tick for the tick burn time of an item.
The electric furnace only consumes 10 eu an operation (100 ticks).

This means that it takes two genertors burning for 400 ticks to power an extractor, but one generator can handle 10 furnaces every 100 ticks.

There is definitely a flaw in the furnace, both in smelting time and energy usage, but I also think the generator is to weak given those rules. so either the recipe/furnace costs per tick would have to be reduced or the generator gen per tick increased.

**Comment by modmuss50** [comment]
I think make the generator make 40 a tick would be more appropriate,

**Comment by xannor** [comment]
40 would exceed the max output of 32. I gave it some thought and I think that 20 eu a tick as the base for a generator, and  scale the other generators off of that change (in essence doubling them unless that would make their output absurd.) and making the furnace consume 20 eu a tick instead of per operation, and leave the tick count at 100, would fix the balance. this would mean one generator could power a furnace for four operations, or the extractor for one. Otherwise you would have to change most of your energy usage for other machines and power storage.

In comparason to vanilla, you would get enough power to smelt 16 items in the time it takes to burn one coal, or run the extractor for 4 operations, all off of one generator.
