### ISSUE TITLE
cables, 1.9.4, and MCMultipart

### ISSUE THREAD

**Issue by Gunner76th** [TechReborn/TechReborn#601]
In game, when you hover over the cables, it says you must have MCMP installed before you can use/place the cables. As of yet, MCMP has not been updated to 1.9.4, and in fact it has not seen an update in almost 2 months. TechReborn has seen numerous updates, several of which have happened  in the last 3 days. 

Have you looked into coding the cables so they do not require MCMP (which contradicts your statement that TechReborn is completely standalone) the same as IC2 and GregTech were able to do in 1.5x, 1.6x, and 1.7.x? 

This leads to my second question and issue. On the Curse site, you state that " In 1.9 the mod is fully standalone ". If this were true, the cables would not require an unrelated mod in order to place them. Also, any mod that requires a core mod, is technically also not fully stand alone as it is depending on a second mod (even if said mod is developed by the same group) in order to operate. I would suggest removing the statement that the mod is fully stand alone, as well as clearly stating in the description that MCMulti Part is required for the cables, as neither the description nor the changes section state anything about requiring MCMulti Part. Failure to list all mod dependencies (even ones that are not technically required for the mod to load) violates the trust of the users and pseudo-rules established by the modding community (aka the Brethren Code).

**Comment by Lanse505** [comment]
This is why MCMP hasn't been updated as far as I know.
https://github.com/MinecraftForge/MinecraftForge/pull/2891

**Comment by covers1624** [comment]
MCMP is being pulled in to forge so the cables have always had this
dependency on them due to down the road MCMP being pulled in to forge.
Guess that it just happended to fall in 1.9.4 to be pulled in to
forge. So, having the cables placeable without MCMP is kinda pointless
because it is just more work when MCMP gets merged.

----- Original Message -----

**Comment by covers1624** [comment]
Also the quote "In 1.9 the mod is fully standalone" Meaning that it is
no longer an addon to IC2.

----- Original Message -----
From: "TechReborn/TechReborn" 
To:"TechReborn/TechReborn" 
Cc:
Sent:Thu, 26 May 2016 15:35:36 -0700
Subject:[TechReborn/TechReborn] cables, 19.4, and MCMultipart (#601)

```
In game, when you hover over the cables, it says you must have MCMP
```

installed before you can use/place the cables. As of yet, MCMP has not
been updated to 1.9.4, and in fact it has not seen an update in almost
2 months. TechReborn has seen numerous updates, several of which have
happened in the last 3 days.  

```
Have you looked into coding the cables so they do not require MCMP
```

(which contradicts your statement that TechReborn is completely
standalone) the same as IC2 and GregTech were able to do in 1.5x,
1.6x, and 1.7.x?  

```
This leads to my second question and issue. On the Curse site, you
```

state that " In 1.9 the mod is fully standalone ". If this were true,
the cables would not require an unrelated mod in order to place them.
Also, any mod that requires a core mod, is technically also not fully
stand alone as it is depending on a second mod (even if said mod is
developed by the same group) in order to operate. I would suggest
removing the statement that the mod is fully stand alone, as well as
clearly stating in the description that MCMulti Part is required for
the cables, as neither the description nor the changes section state
anything about requiring MCMulti Part. Failure to list all mod
dependencies (even ones that are not technically required for the mod
to load) violates the trust of the users and pseudo-rules established
by the modding community (aka the Brethren Code).  

```
—
```

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2].     

## Links:

[1] https://github.com/TechReborn/TechReborn/issues/601
[2]
https://github.com/notifications/unsubscribe/ABTl6rC3fa0RV2ZOqGmC_TohmwBApZeDks5qFiA4gaJpZM4IoBFs

**Comment by Prospector** [comment]
I will update the curse description for clarity

**Comment by Rukachan** [comment]
> As of yet, MCMP has not been updated to 1.9.4

Please avoid making incorrect claims, MCMP has been updated to 1.9.4

> and in fact it has not seen an update in almost 2 months

The last "official" experimental build was made 5 days ago, same for the last change at the public github repo.

**Comment by Sailren** [comment]
where is the download link for 1.9.4 for mcpc sherlock holmes?

**Comment by modmuss50** [comment]
I know where it is, but I'm not going to link it

**Comment by Sailren** [comment]
its not on the curseforge page, that's for sure

**Comment by modmuss50** [comment]
It's not there for a very good reason

**Comment by Sailren** [comment]
okay sounds promising

**Comment by asiekierka** [comment]
@Sailren - It's not linked because compatibility between 1.9.4 MCMP and 1.9.4 FMP might be a bit wonky, as well as confusing users etc. Same reason I pulled the 1.9.4 Charset build, even though it existed, some people have it and some people play it while it depends on MCMP :)

**Comment by Gunner76th** [comment]
From a user's perspective, as well as a MC Server admin's. if the link is not publically available, and the only links for it are for older outdated version, then as far as the public is aware and concerned, it has not been updated. 

If you have updated to 1.9.4, but to not have the updated version where it can be accessed, then the update means nothing to the public. er-go my previous statement still stands true (unless you have now released a public link to a 1.9.4 version of MCMP), that no update to MCMP for 1.9.4 exists, and has not been updated for said duration (as far as the public is aware and can see by all Reasonable methods.  I do see where there was a commit to the github 5 days ago, however I am unable to locate a link for that update within the github repo.

You can update a mod all you like, but until a link is posted where normal users are able to download and use your updated mod, the update does not matter in regards to this specific thread and issue, as your mod does not have a identifiable method of obtaining it publicly for use.

**Comment by asiekierka** [comment]
I have updated to 1.9.4, I had the link accessible for a few days - even linked on Charset's website, but when circumstances changed I pulled it. (It also came with the necessary MCMP version)

What does that make it? A mod which was updated and then suddenly became un-updated?

**Comment by Rukachan** [comment]
> From a user's perspective, as well as a MC Server admin's

From a user's perspective, as well as a MC Server admin's if the source exists in the github repository and building it is as trivial as running `gradle build` then as far as the public is aware and concerned, it HAS been updated.

> however I am unable to locate a link for that update within the github repo.

I actually am (tip: it's in the README.md), but even if it was not, it would be irrelevant due to the above.

As for the rest, you are introducing an extra requirement to patch the incorrect logic of the original post. It is a fact that the mod has been updated and that makes the original post wrong, it does not matter about what the "public" is aware and concerned about as that requirement was not in the original post and as it is a fact that it has been updated.
Let's take an example, people commonly think the size of a byte is 8 bits, but does this not make it correct. Saying that "1 byte = 8 bit" simply because this is what the majority of people believe is incorrect.
Now, you come to the topic and say "no because as far as the public is aware and concerned", well, too bad, "as far as the public is aware and concerned" is not equivalent with stating something as a global fact.

**Comment by modmuss50** [comment]
I dont know what the fuck this conversation has turned into. If you want to continue to argue do it somewhere else. Thanks,
