### ISSUE TITLE
1.10.2 - TCon and TechReborn Crash

### ISSUE THREAD

**Issue by Peach774** [TechReborn/TechReborn#664]
1.10.2 LAN - Scrolling through the tinkers construct creative menu and reachieved this crash, since it mentions both tech reborn and tinkers construct I will also be posting this on their github.
http://pastebin.com/8mg4bckf

**Comment by KnightMiner** [comment]
This issue is twofold. First is what causes the crash, that being an off by one error in `getStateFromMeta()`. [This check](https://github.com/TechReborn/TechReborn/blob/1.9.4/src/main/java/techreborn/blocks/BlockStorage.java#L91) should use `>=` and not `>`.

Second is the fact that an [invalid block is being oredicted](https://github.com/TechReborn/TechReborn/blob/315c0aa509376d57e56acb04680cc6b88afb8857/src/main/java/techreborn/init/ModBlocks.java#L493). Metadata 14 is invalid according to the block class but is registered as "Iridium", which Tinkers construct pulled from the oredict for its automatic table textures. Metadata 13 where it should be is instead registered as "Osmium"

**Comment by Peach774** [comment]
Any sort of update on this issue? Still causing crashes.

**Comment by Rushmead** [comment]
@modmuss50 either add more types here: https://github.com/TechReborn/TechReborn/blob/1.10/src/main/java/techreborn/blocks/BlockStorage.java#L27 or remove the Osmium from the oreDict here:https://github.com/TechReborn/TechReborn/blob/315c0aa509376d57e56acb04680cc6b88afb8857/src/main/java/techreborn/init/ModBlocks.java#L493

**Comment by modmuss50** [comment]
I'm not at a pc for the next 3 weeks. Someone will have to PR in the fix it you will need to wait.

Sorry

**Comment by modmuss50** [comment]
Working fine in 1.10.2, please test again and open another issue

**Comment by KnightMiner** [comment]
You might still want to fix the check [here](https://github.com/TechReborn/TechReborn/blob/1.9.4/src/main/java/techreborn/blocks/BlockStorage.java#L91) so if you do accidentally oredict a wrong number again it does not crash. Right now it would cause a similar crash if you were to give your self a storage block with a metadata of 14

**Comment by modmuss50** [comment]
I think I fixed this a while ago, it hasn't been brought to my attention recently so closing.
