### ISSUE TITLE
Silver Ore & Lead Ore OR Galena Ore?

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#776]
It doesn't make much sense to have both. Somehow we should remove either the silver & lead ores, or the galena ore. Hopefully in a way without corrupting worlds. Maybe we could replace all silver and lead ores with galena ores in world?

**Comment by modmuss50** [comment]
Not easy to change block meta data without causing excessive chunk loading lag

**Comment by ghost** [comment]
Perhaps you could phase it out, so old chunks are untouched, any new chunk generation will only generate galena, but the mod will still have compatibility with lead and silver ores for the foreseeable future?

**Comment by modmuss50** [comment]
Yeah that would be a good idea, I will think about it.

**Comment by ChubbyTurtle101** [comment]
Suggestion is to keep the Galena Ore and maybe have a slight chance for one block be Silver or pure Lead as it helps to have as easy to process lead or silver in the early game and then wait until you get more machines to process the Galena.  You could update textures to use the Galena texture with more lead or silver pixels so it all blends in.  Real ore have pockets where you have more lead or more silver instead of always half and half.  Also would be nice to centrifuge the Galena into lead and silver dusts instead of having to put it in an industrial blast furnace.

**Comment by Prospector** [comment]
I like that idea a lot ^
