### ISSUE TITLE
Rolling machine is broken

### ISSUE THREAD

**Issue by DreiPixel** [TechReborn/TechReborn#783]
hello there,
we use MC 1.10.2 and the latest TechReborn (1.4.7.70) on our server.

the Rolling machine does... nothing... it looks like it doesnt even get power.

**Comment by modmuss50** [comment]
Oh that's strange O_o

**Comment by utoc** [comment]
According to TheOneProbe, it looks like the rolling machine gets power, however, the indicator in the gui doesn't show that it does.

http://i.imgur.com/LGEby61.png

The issue here is the recipe:  
`
.addRollingOreMachinceRecipe(ItemParts.getPartByName("cupronickelHeatingCoil"), "NCN", "C C", "NCN", 'N', "ingotCupronickel", 'C', "ingotCopper");
`

But as seen in the linked image below, only ingotCopper shows up; we do not have ingotCupronickel.  I'm not sure if this is intended: http://i.imgur.com/ab93j5C.png?1

Also, and this is a separate issue, it doesn't look like modTweaker has a handler for techreborn.rollingMachine.addRecipe.  I was going to add a workaround for the coil but this is one of the new machines that doesn't work with MT.

**Comment by modmuss50** [comment]
Ok, so it sounds like the gui isnt showing the power
and the recipe needs to be using copper for everything
and it needs minetweaker support.
