### ISSUE TITLE
Generators are broken.

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#838]
They can accept any fluid

**Comment by Ourten** [comment]
Inside a GasTurbine when a unvalid fluid (like water) is inserted it try to check in this map https://github.com/TechReborn/TechReborn/blob/1.11/src/main/java/techreborn/tiles/generator/TileGasTurbine.java#L42 to get the fuel value, however if the fluid isn't present it will return a null Integer object, inducing a NullPointer when evaluating the amount to consume per tick : https://github.com/TechReborn/TechReborn/blob/1.11/src/main/java/techreborn/tiles/generator/TileGasTurbine.java#L121

I think that this issue could be fixed by creation of a unified recipe system for the generators, allowing them to check it before accepting any fluid.

**Comment by Ourten** [comment]
Fixed in [97192ee](https://github.com/TechReborn/TechReborn/commit/97192ee3f4c44d27779b33958772d23854170083)
