### ISSUE TITLE
How to get Iridium Ingots?

### ISSUE THREAD

**Issue by davqvist** [TechReborn/TechReborn#886]
Forge 12.18.3.2185
RebornCore 2.8.5.79
TechReborn 1.4.16.133

I don't understand the Iridium plan. You can get Iridium Ore from UU-Matter but the only weird use seems to get infinite Platinum from the Grinder. Iridium Nuggets you get from Sheldonite, but there are no uses either. And then you can get Iridium Plates from 4 Iridium Ingots (which are unobtainable) in a Implosion Compressor, but you can get them from one Ingot in a normal Compressor (why would you use the first recipe?). There seem to be missing and not fitting recipes.

**Comment by Prospector** [comment]
This is fixed in 1.11.2. Iridium Ore is used in an industrial grinder to get iridium ingots and some platinum. Then you can either use 9 iridium ingots to make 1 iridium plate, or use 4 iridium ingots and some other materials to make an Iridium Alloy Ingot, to implosion compress into an iridium plate.
