### ISSUE TITLE
No Way To Get Mixed Metal Ingot

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#890]
Using forge 1.11.2-13.20.0.2204. using game 1.11.2. using mod version 2.0.9.16. can not get mixed metal ingot. and why cant we get lazurite dust from grinder? and some other dusts. because generating an industrial grinder is very hard, expensive. 
using jei 4.2.2.220. thanks

**Comment by rayronqween** [comment]
I have the same issue using TechReborn-1.11.2-2.0.9.16-universal.jar  for my 1.11.2 modpack. its a major issue because you can't craft advanced machine block which needs Advanced alloy ingot which needs the mixed metal ingot. This makes any industry machines uncraftable. Also if you can please add nickel ore. only way to get it currently is by an industrial machine which you can't get lol. also for coal dust would recommend coal to coal dust instead of coal ore; needing silk touch for coal dust is silly imho. 

http://wiki.industrial-craft.net/index.php?title=Mixed_Metal_Ingot       missing recipe

**Comment by ghost** [comment]
yea and also can not build a solar panel :D

**Comment by Prospector** [comment]
New build will be up shortly. I forgot to call the method that added the recipes :P

I will be looking into alternative methods of obtaining nickel.

**Comment by Prospector** [comment]
@rayronqween Which industrial machine do you need nickel for? I am confused to what you mean.
